AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2SSMRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EC2-SSM-Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"

  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: "EC2-SSM-InstanceProfile"
      Roles:
        - Ref: "EC2SSMRole"

Outputs:
  EC2SSMRoleArn:
    Value: !GetAtt EC2SSMRole.Arn
  EC2InstanceProfileName:
    Value: !Ref EC2InstanceProfile
